# Generated by Django 3.2.13 on 2022-05-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1994-04-22'),
            preserve_default=False,
        ),
    ]
